### ISSUE TITLE
Unable to fire change() on mvc.collection

### ISSUE THREAD

**Issue by gmkumar2005** [rhysbrettbowen/PlastronJS#3]
I have a menumodlelist it contains menumodel. I need a event to be fired when model changes. My changes are bulk ie, i need one event after sucessful update of all menumodels. I am listening with anyModelChange as well as modelChange. Either of them dont fire even after a call to change(). Below is the test case the assertion at the end fails.
Thanks Kiran

``` javascript
var menuModel1;
var menumodellist = new mvc.Collection({
    'modelType': bs.models.menuModel,
    'name': 'menumodellist'
});

var setUp = function() {
    menuModel1 = new bs.models.menuModel();
    menumodellist.add(menuModel1);
};

var testChangeListner = function() {

    var ran = 0;
    var bindfn = function() {
        ran++;
    };
    menumodellist.anyModelChange(bindfn);
    menumodellist.modelChange(bindfn);

    menuModel1.set('isChecked','one',false);
    assertEquals(1, ran); //anyModelChange executed as expected

    menuModel1.set('isChecked','one',true);
    assertEquals(1, ran); // events should not fire

    menumodellist.change();
    assertEquals(2, ran); // FAILS here. I expect bindfn executed due to modelChange()
};
```

**Comment by rhysbrettbowen** [comment]
in this case menumodellist.change() is going to fire for any attributes on menumodellist, not on the models beneath it. This is because menumodellist is a collection, but it inherits from models so it has it's own attributes. what you can do is fire a change for each model under menumodellist like so:

goog.array.forEach(menumodellist.getModels(), function(child) {child.change();}});
